set_location_assignment PIN_18 -to clk
set_location_assignment PIN_23 -to sw1
set_location_assignment PIN_21 -to dip\[1\]
set_location_assignment PIN_22 -to dip\[0\]
set_location_assignment PIN_37 -to seg\[0\]
set_location_assignment PIN_38 -to seg\[1\]
set_location_assignment PIN_39 -to seg\[2\]
set_location_assignment PIN_40 -to seg\[3\]
set_location_assignment PIN_41 -to seg\[4\]
set_location_assignment PIN_42 -to seg\[5\]
set_location_assignment PIN_43 -to seg\[6\]
set_location_assignment PIN_44 -to seg\[7\]
set_location_assignment PIN_29 -to dig1
set_location_assignment PIN_30 -to dig2
set_location_assignment PIN_31 -to dig3
set_location_assignment PIN_32 -to dig4
set_location_assignment PIN_1 -to led1
set_location_assignment PIN_2 -to led2
set_location_assignment PIN_3 -to led3
set_location_assignment PIN_5 -to led5
set_location_assignment PIN_6 -to led6
set_location_assignment PIN_7 -to led7

