set_location_assignment PIN_18 -to CLK
set_location_assignment PIN_23 -to SW1
set_location_assignment PIN_24 -to SW2
set_location_assignment PIN_27 -to SW3
set_location_assignment PIN_28 -to SW4
set_location_assignment PIN_37 -to SEVEN_SEG\[0\]
set_location_assignment PIN_38 -to SEVEN_SEG\[1\]
set_location_assignment PIN_39 -to SEVEN_SEG\[2\]
set_location_assignment PIN_40 -to SEVEN_SEG\[3\]
set_location_assignment PIN_41 -to SEVEN_SEG\[4\]
set_location_assignment PIN_42 -to SEVEN_SEG\[5\]
set_location_assignment PIN_43 -to SEVEN_SEG\[6\]
set_location_assignment PIN_44 -to SEVEN_SEG\[7\]
set_location_assignment PIN_29 -to Dig1
set_location_assignment PIN_30 -to Dig2
set_location_assignment PIN_31 -to Dig3
set_location_assignment PIN_32 -to Dig4
